import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:image_picker/image_picker.dart';
import 'package:http/http.dart' as http;
import 'package:mime/mime.dart';
import 'package:path/path.dart' as path;
import 'package:uuid/uuid.dart';
import 'package:nutricook/services/presigned_url_service.dart';
import 'package:nutricook/utils/cloudflare_config.dart';

/// Exception thrown during image upload
class UploadException implements Exception {
  final String message;
  final dynamic originalError;

  UploadException(this.message, [this.originalError]);

  @override
  String toString() => 'UploadException: $message${originalError != null ? '\n$originalError' : ''}';
}

/// Service for uploading images to Cloudflare R2
/// 
/// Uses pre-signed URLs generated by the backend to securely upload files.
/// This keeps R2 credentials safe on the server only.
/// 
/// Handles:
/// - Generating unique filenames
/// - Determining MIME types
/// - Requesting pre-signed URLs from backend
/// - HTTP PUT requests to R2 with pre-signed URLs
/// - Returning public URLs
class R2UploadService {
  static const uuid = Uuid();
  late final PresignedUrlService _presignedUrlService;

  R2UploadService() {
    _presignedUrlService = PresignedUrlService();
  }

  /// Uploads an image file to Cloudflare R2
  /// 
  /// Parameters:
  /// - [imageFile] or [imageXFile]: The image to upload
  /// - [folder]: Folder path in bucket (e.g., 'recipes', 'ingredients', 'users')
  /// - [customFilename]: Optional custom filename (without extension)
  /// 
  /// Returns the public URL of the uploaded image
  /// 
  /// Throws [UploadException] if anything goes wrong
  Future<String> uploadImage({
    File? imageFile,
    XFile? imageXFile,
    required String folder,
    String? customFilename,
  }) async {
    try {
      // Get the file to upload
      final File file;
      if (imageFile != null) {
        file = imageFile;
      } else if (imageXFile != null) {
        file = File(imageXFile.path);
      } else {
        throw UploadException('Either imageFile or imageXFile must be provided');
      }

      // Verify file exists
      if (!await file.exists()) {
        throw UploadException('Image file does not exist');
      }

      // Read file bytes
      final bytes = await file.readAsBytes();

      // Generate object key
      final objectKey = _generateObjectKey(
        folder,
        file.path,
        customFilename,
      );

      // Get filename with extension
      final fileName = path.basename(file.path);

      // Determine MIME type
      final mimeType = _getMimeType(file.path);
      if (mimeType == null) {
        throw UploadException('Could not determine MIME type for file');
      }

      // Upload to R2
      final uploadUrl = await _uploadToR2(
        objectKey,
        bytes,
        mimeType,
        fileName,
      );

      if (CloudflareConfig.debugMode) {
        debugPrint('[R2] Upload successful: $uploadUrl');
      }

      return uploadUrl;
    } catch (e) {
      if (e is UploadException) rethrow;
      throw UploadException('Failed to upload image', e);
    }
  }

  /// Generates a unique object key for the file
  /// 
  /// Format: {folder}/{uuid}_original_filename.ext
  String _generateObjectKey(
    String folder,
    String filePath,
    String? customFilename,
  ) {
    final originalName = path.basenameWithoutExtension(filePath);
    final extension = path.extension(filePath);
    final fileName = customFilename ?? originalName;
    final uniqueId = uuid.v4().substring(0, 8);
    final objectKey = '$folder/${uniqueId}_$fileName$extension';
    return objectKey;
  }

  /// Determines the MIME type of a file
  String? _getMimeType(String filePath) {
    try {
      return lookupMimeType(filePath) ?? 'application/octet-stream';
    } catch (e) {
      debugPrint('Error determining MIME type: $e');
      return 'application/octet-stream';
    }
  }

  /// Uploads file to R2 using a pre-signed URL from the backend
  /// 
  /// Returns the public URL of the uploaded object
  Future<String> _uploadToR2(
    String objectKey,
    List<int> fileBytes,
    String mimeType,
    String fileName,
  ) async {
    try {
      // Extract folder from objectKey (format: "folder/uuid_filename.ext")
      final folder = objectKey.split('/').first;
      
      // Request pre-signed URL from backend
      final presignedUrl = await _presignedUrlService.getPresignedUrl(
        folder: folder,
        fileName: fileName,
        mimeType: mimeType,
      );

      if (CloudflareConfig.debugMode) {
        debugPrint('[R2] Got presigned URL, uploading ${fileBytes.length} bytes...');
      }

      // Upload using pre-signed URL (no authentication header needed)
      final response = await http.put(
        Uri.parse(presignedUrl),
        headers: <String, String>{
          'Content-Type': mimeType,
        },
        body: fileBytes,
      ).timeout(
        const Duration(minutes: 5),
        onTimeout: () {
          throw UploadException('Upload request timed out');
        },
      );

      if (response.statusCode != 200) {
        throw UploadException(
          'Upload failed with status ${response.statusCode}',
          response.body,
        );
      }

      // Return public URL
      return CloudflareConfig.getPublicUrl(objectKey);
    } on UploadException {
      rethrow;
    } catch (e) {
      throw UploadException('Network error during upload', e);
    }
  }
}
