// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAJXRqJU790aaMge2ZN14_5p3eoPd16vQ',
    appId: '1:482853364044:web:9c137e70f408ee165befe9',
    messagingSenderId: '482853364044',
    projectId: 'nutricook-2305',
    authDomain: 'nutricook-2305.firebaseapp.com',
    storageBucket: 'nutricook-2305.firebasestorage.app',
    measurementId: 'G-01V0NMB9HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGqgKyjlsXUcx4LFiGJohdKqazINtiLTo',
    appId: '1:482853364044:android:38b5a67db3ffae165befe9',
    messagingSenderId: '482853364044',
    projectId: 'nutricook-2305',
    storageBucket: 'nutricook-2305.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3pHwlKAC0B8V1HK7gEhWLJXGIoAg-yFI',
    appId: '1:482853364044:ios:031655a4710f77cf5befe9',
    messagingSenderId: '482853364044',
    projectId: 'nutricook-2305',
    storageBucket: 'nutricook-2305.firebasestorage.app',
    iosBundleId: 'com.proj.nutricook',
  );
}
